language: go

go:
  - master

notifications:
  email: false

go_import_path:
  #/

before_install:
  - mv $HOME/gopath/src/github.com/CODEJY/ServiceComputing/Agenda_hw2 $HOME/gopath/src

#install: true

script:
  - cd $HOME/gopath/src/github.com/CODEJY/ServiceComputing/Agenda_hw2 
  - go test -v ./...
